### PR TITLE
Chp 8 Exercise write up

### PR DESCRIPTION
**Pull request by bkarger**

### CODE REVIEW

**Comment by geanders** [comment]
@bkarger : Great start on this! I've listed some suggestions for edits below. Please go through those. If you make changes on your computer and push them to your GitHub, then they should come through in this pull request as long as we keep it open (email me when you do just in case, so I can make sure).

- That's great that you've posted the exercise prompt from the book. I suggest that you put it in a "quote" environment so it will stand out as something different. All you need to do for that is use "> " at the start of the paragraph that you want to quote. For example, you can change (I've also changed a touch of other formatting in this example): 

```
edgeR. Do the analyses of Section 8.5 with the edgeR package and compare the results: make a scatterplot of the 
log 10 p-values, pick some genes where there are large differences, 
and visualize the raw data to see what is going on. Based on this can you explain the differences?
```

to 

```
> **edgeR.** Do the analyses of Section 8.5 with the `edgeR` package and compare the results: make a scatterplot of the 
log 10 p-values, pick some genes where there are large differences, 
and visualize the raw data to see what is going on. Based on this can you explain the differences?
```

- Throughout, could you edit to typeset the package names in the code formatting (that is, with backticks around them)? You do this some places, but not everywhere. It really does help, because it helps readers' brains immediately identify that it's not a word they need to process in English.
- Nice job in explaining the code to load the data and convert it to a matrix. However, could you edit to make this sentence a complete one: "Subsequent conversion to a matrix object."? Also, after you show this data, could you add a bit of explanation about what the data is showing? For example, how was it collected, what do the columns measure, what does each row measure, and what are the dimensions?
- There's a typo: "Rstuio". (Also, after this word, in the text could you add "with", and after "online" in this sentence, could you at "at"?)
- Very nice job throughout of pointing the reader to other resources for following up (for example, the `edgeR` vignette and the reference links at the end of the post).
- I recommend that you change "consisting of the 8 samples" to ", which is a vector with values representing the treatment status of each of the 8 samples".
- For "Calculate normalization factors to scale the raw library sizes.", could you expand on this a bit to explain exactly what's done in this scaling / normalization process? Is it a classic scaling, where you center and divide by the standard deviation? Or is this the process of normalizing *across* samples, by assuming that the values of the vast majority of measurements should be about the same (non-differential) across samples, and so you can tell by looking at average values (or some other measure across the sample) which happen to have consistently higher or lower values, and bring everything back down to the same baseline? I think this is a key step in processing this type of data, and one where it's helpful to know how it's being done so that you can be clear about what assumptions you're leaning on to do it, so this would be a great spot to add some discussion.
- Could you add a bit of text to explain why you're doing the `model.matrix` step?
- I think you probably want to take out "Usage" from the quoted definition for `estimateDisp` (I'm guessing that you copy just a touch too much from the help file.)
- It's great that you explained why we're using the negative binomial here!
- In this section, could you also add just a bit of explanation on estimating the dispersion? You're almost there---you've explained why we need to estimate dispersion. However, if we had loads of samples, we could just estimate this when we fit the models in the next step. We don't, though (only, what, 8 samples? that's not a lot of data to fit a model with, especially if you need to estimate two or more parameters, and here we're going to want to estimate (1) the mean intensity of the gene expression in the untreated; (2) the difference in mean intensity between the untreated and the treated; and (3) the dispersion parameter). The magic they're using here is this idea that they can "borrow" information from measurements of other gene's expression levels when they estimate this dispersion parameter for each gene. That helps them get around this challenge of not having enough samples to estimate it cleanly for each gene, and leverages the fact that, while we don't have lots of samples for each gene, we have *loads* of different genes that were measured, and so a lot of data in that dimension. They go a bit more into this idea in section 8.10.1 of the chapter. You might want to revisit that section to help with adding a bit of discussion on this idea here. I think that the vignettes for `edgeR` and `DESeq2` should have some on this idea, too. 
- There's a typo: "probility"
- Really nice explanation of why we picked the regression model that we did. However, could you also add what our goal is in fitting this model for each gene? Ultimately, we're trying to identify genes where the intensity level (expression) is notably different between the treated samples and the untreated samples, right? I think that overarching goal is missed a bit right now in the explanation.
- Could you show a bit more what you have once you've created the `qlf` and `edgeRoutput` objects? It would be really helpful to show the reader a summary of what's in these objects, and what parts you might want to investigate to answer your scientific question (which genes have notably different levels of expression in treated versus untreated samples, for example). Right now, you move right past this to start comparing with the `DESeq2` output, but I think it would be great to take just a bit more time to show what you get from `edgeR` before you move into that comparison part.
- Yah "Tidyverse" magic! However, the convention is to always spell "tidyverse" in all lowercase. Since package names are case-sensitive in R, this is an important style point to follow (for some other programming languages, there are actually cases where people have made malicious code packages with names that are very similar to or easy misspellings of popular packages, so that people download and execute malicious code on their computer...).
- Along the way with your tidyverse magic, could you show what your data looks like and what your goal is in transforming it? It looks like you're pulling data out of an S4 object, from the output of `edgeR` operations, maybe?, then pulling the rownames into a new column so you can use the information embedded in them, and then cleaning up a bit by limiting to just the columns that you need and by rearranging the order of the rows so that the genes with the lowest p-values show up first. Some brief explanation along those lines would be helpful to readers.
- Is the `pasilla` data the output from running the same process but using `DESeq2`? If so, I'm not sure that was clear in the current write-up. That is really great to compare the results from the two different packages, as I think that the heart of this question is really for you to explore how similar / different they are and whether your conclusions with one are similar to those with the other (ideally, we wouldn't want a major scientific finding to disappear if you ran the same data with the other package, which I imagine has the same goal but uses a slightly different algorithm). Could you add some text explaining that you're comparing the results from these two different packages in these plots at the end of the post?
- Nice use of log-10 transforms in your plots of the p-values, to help in showing those very low values. You should also check out transforming via transformations to the x- and y-axis scales themselves, rather than transforming the variable before plotting it. You could check out `scale_x_log10` and `scale_y_log10` for doing this. 
- Also for this plot, could you clarify on the x- and y-axis labels which axis shows the results from `edgeR` and which from `DESeq2`? I think the "pvalues" / "Pvalues" distinction is a bit unclear---this is just relying on quirks in the names used inside the output objects for the two packages and wouldn't be clear to any reader that doesn't use those packages a lot. Instead, I think it would be better to have the axis titles say something like "p-values from DESeq2 analysis" and "p-values values from edgeR analysis". In the subtitle for the plot, it would be helpful to explain that each point represents a single gene, and the p-value is for a hypothesis test of whether the gene has a notably different expression level between treated and untreated samples.
- In this plot, it would also be helpful to have a reference showing where points would fall if they were identical between the two methods. You could try using `geom_abline` to add a line with an intercept of zero and a slope of 1 to do that (this will probably only work if you use the `scale_x_log10` approach for taking log transforms, rather than converting with `log10` in the `aes` statement). 
- For your statement, "most of the data are falling on top of each other when pvalue > -25"---I wonder if this is true, or if this is more of a relic of the log-transform smooshing some of that data, so it looks closer on x- and y- dimensions that it really is?
- When you mention "pvalue < -25 (log10 values)", I think it would be clearer to put "log10(pvalue) < -25". This shows up both in the text and in the title of the last plot.
- It wasn't clear to me what you meant by, "When plotting these we don’t see any overlapping, showing that there are some variations between the edgeR and DESeq2 packages." Could you clarify this wording?
- Overall, very nice and thorough job!

**Comment by bkarger** [comment]
Hi Brooke,

I know you'll probably get a notification of my pull request but since
class is tomorrow I figured I'd also send an email!

Thank you for the edits I learned a lot reading that vignette a little
deeper for edgeR.

Burton

**Comment by geanders** [comment]
@bkarger : Great! This is now published: https://kind-neumann-789611.netlify.app/post/ex-8-1/

**Comment by bkarger** [comment]
Hi Brooke,

I did one final pull request to fix some edits I found today while reading
it before class. Sorry to make a request an hour and a half before class.

I might be a bit late today but I plan to make it in time to present.
Another out of the blue barrier day I'm afraid!

Burton

**Pull request merged**
