### PR TITLE
Vocal 2.8-2.12

### PR DESCRIPTION
**Pull request by pughs**
Let me know what I need to fix. Not super confident in bio words :) Oh, and changing the date (at least where I did) didn't seem to hid the post until then. Did I just do that in the wrong spot?

Also, I experimented with .gitignore so let me know if I broke anything.

### CODE REVIEW

**Comment by geanders** [comment]
@pughs : This is looking really great! For the date, I think that the post will show up on your local computer, but not on the online version, before the posted date. So we should be fine on that.

I'll let @baileyfosdick and @lyonsm7 chime in, but here were a few suggestions I had for the vocab terms (I've formatted these as checkboxes, in case you'd like to check off as you go): 

- [ ] For the *prior* and *posterior*, do you think it would be clearer to change "collecting data" to "incorporating new data" or something else that clarifies the integration process of the new data?
- [ ] For *haplotype*, I think it might be good to change "spatially adjacent" to "spatially close". I think that sometimes the alleles in haplotypes might not be touching (adjacent), but are close. 
- [ ] Also for *haplotype*, I recommend changing "collection of alleles (DNA sequence variants)" to "a collection of DNA sequence variants (e.g., alleles)". It [sounds like](https://www.genome.gov/genetics-glossary/haplotype) a haplotype can be a set of SNPs, rather than alleles.   
- [ ] For *marginal distribution*, I'd recommend just using the general definition you give ("the distribution of a sub-collection of variables after integrating out the remaining variables in the collection"). 
- [ ] For the *mixture* definitions, is there a way you can change it to not include the word "mixture" in the definition? Would "combination" work instead? Also, for this definition, since "mixture" can mean a lot of different things, I think it would be useful to add "In the context of statistics" or something similar.
- [ ] For *codon bias*, I recommend taking out "describes" and changing "the difference" to "differences".

All the .gitignore additions look sensible to me. I don't anticipate any problems from those. The "Sources cited" and "Practice sections look great, but do make sure that you go on Quizlet and update your vocab list with the final versions of all the definitions once you've incorporated any changes from Mike, Bailey, or me. We'll leave the pull request open, so as long as we do I think that any other changes you make and push to your version of the repo on GitHub should be added in to this PR, and you shouldn't have to set up a second one. Add a note here when you're done with any changes, though, so we can confirm. 

Great work!

**Comment by geanders** [comment]
@baileyfosdick and @lyonsm7 : @pughs has addressed all the changes I had to suggest for this vocabulary. If you have any suggestions, let us know. As soon as we're happy with the words, I'll work on accepting and integrating the pull request so we'll have this ready to go on the website a week before next week's class.

**Comment by baileyfosdick** [comment]
@pughs This looks great. I think we are missing a few terms though.  For example, in my (hard copy) of the book, the following words are bolded but not in the list:  Bayesian paradigm, beta distribution, exponential distribution.  Can you add these three terms?

**Comment by geanders** [comment]
Very nice work on this, @pughs ! I have merged your pull request and will get your post up on the site sometime today.

**Comment by geanders** [comment]
@pughs : It's now [up](https://kind-neumann-789611.netlify.com/post/vocabulary-for-chapter-2-8-2-12/)! 

It turns out that we cannot gitignore some of the files, like ".html" files. We're doing the local conversion from .Rmd to .html on our own computers, and then Hugo "builds" the site from the files pushed to github, but I don't think that Hugo can process the .Rmd to .html, so we have to do that and make sure the .html gets to GitHub (I think). In any case, I think we've got it all working now!

**Pull request merged**
