### PR TITLE
Vocabulary List for Chapter 8

### PR DESCRIPTION
**Pull request by melder27**
Created a blog post for the Vocabulary List for Chapter 8

### CODE REVIEW

**Comment by geanders** [comment]
@melder27 : This looks really great! I just had a few small comments, and then I'll pass along to Bailey for her final okay and get the post up. 

- Throughout the terms, could you change so that only proper nouns are capitalized? Right now, the first word of each term is capitalized, but I think it's helpful for people to learn which of these words are proper nouns that should always be capitalized versus which are not, and I think using lowercase in the terms whenever possible will help with that.
- Could you double-check that the Greek letters in the vocab list (alpha and beta in the definition for "gamma-Poisson", for example) are rendering okay in the Quizlet app"? (You can just try out the quizlet app until you get to this definition to confirm.) If not, could you change to just spell out "alpha" and "beta", etc., in the definitions?
- For the definition of "Systematic biases", could you try to edit the definition so that it does not include the word "biases"? (For example, maybe use "systematic distortions" instead.)
- In the definition of "balanced", could you change "there is" to "there are"?
- For the definition of "batch effects", I'm wondering if it's currently a bit too general? I usually think of this as what you describe, but specifically for patterns that emerge from how the experiment was processed (for example, that samples run at the same time have a degree of similarity from being run in the same batch).
- There is a typo in the definition of "Regularized logarithm (rlog) transformation" ("withh")
- I think that the definition for "Cook's distance" might be a bit too specific. I don't think it *has* to be only for data for a gene. Could you take a second look and see if that definition should be edited to be more general?
- For the definition for "Sampling without replacement", could you change "that" to "in which"?
- For the definition of "conservative", I think it's currently a little too strict. I think you can have a method that is conservative but still results in *a few* false positives, it's just that conservative methods prioritizing *reducing* false positives (but not necessarily eliminating them completely).

If you make these on your computer and push the changes to your GitHub fork of the repo, they should automatically get added on to this pull request, since we still have it open. Once you do that, if you could email us and let us know, @baileyfosdick can do a last check, and then we'll post for the class.

**Comment by melder27** [comment]
Hi Dr. Anderson,

Thanks for the feedback! I fixed a few extra typos on top of the ones you caught using the Grammarly app. 

- I fixed the capitalization to just proper nouns. Let me know if you find something that didn't get fixed.

- The greek letters looked okay on the Quizlet website for gamma-Poisson.

- I fixed the grammatical things in the other definitions, but please double-check the definitions for: conservative, Cook's distance, and batch effects. Specifically for batch effects, I tried to define it without specifically using the word 'batch' but coming from a biological background, the synonyms for batch didn't seem to have the same meaning in an experimental setting. I'm open to suggestions though if you or Dr. Fosdick would like it changed to something else. 

I updated the Quizlet and tsv file with all of the changes. Please let me know what else you need from me! Thanks for your time, help, and patience!

Thanks,
Mikaela

**Comment by geanders** [comment]
@baileyfosdick : I think we're ready for you to take a look at the vocab list when you get the chance. Once you add any suggestions you have, I'll post this on the site.

**Comment by baileyfosdick** [comment]
@geanders Good to go!

**Comment by geanders** [comment]
Great! I will get this on our website. @melder27 , would you make sure that the Quizlet app definitions are up-to-date with Bailey's additions? You can see her updates in her commit: https://github.com/geanders/csu_msmb/pull/57/commits/264aab5580583c31fac924a117cb1e5e67bba058

**Comment by melder27** [comment]
@geanders I will do that now! Thanks again for your time and help!

**Comment by melder27** [comment]
Quizlet is down, but I will keep checking today to update the Quizlet app!

**Comment by geanders** [comment]
Sounds good. It's been doing that, but usually is up very, very quickly (a minute or two), so you could check again very soon.

**Comment by melder27** [comment]
Quizlet has been updated!

**Comment by geanders** [comment]
Wonderful, thanks!

**Pull request merged**
