### PR TITLE
Chapter 10 vocabulary attempt

### PR DESCRIPTION
**Pull request by sarahcooper22**

### CODE REVIEW

**Comment by geanders** [comment]
Dear @sarahcooper22 : 

Really nice start on this! I have some suggestions for some updates to the definitions. Once you take a go at these, @baileyfosdick can take a final look, and then we can get the post up. 

- There may be a few terms for the chapter that show up in bold in the print version but not online. We've listed all the terms for this chapter here: https://github.com/geanders/csu_msmb/issues/46
Could you double check that against your list and make sure there aren't a few missing?
- Throughout, could you change all the definitions to start with the same capitalization? (either always start with a capital letter or never start with a capital letter)
- For the terms, could you change the capitalization so it only starts with a capital letter if it's a proper noun?
- For "graph", could you add at the beginning of the definition "a structure"?
- For "adjacency matrix", I recommend taking off the "A" at the end of the term right now. I was just checking the book, and it looks like that's just a notation they're using in the book, rather than part of the term itself. Also, for the definition, could you add "of a graph" after "the edges"?
- For "sparse" and "dense", they can have meanings outside of graphs. I recommend editing those definitions to start with "In the context of graphs,"
- For "arrows / directed edges", could you add at the beginning "Graph edges that" and change "connects" to "connect" (since "edges" is plural in the term)?
- For "annotation variables" could you start with "Graph visualization characteristics that"?
- For the term "Graph layout", would you change it to "Graph layouts" so that it will agree (as a plural) with the wording in the definition?
- I think that the definition for "bipartite graph" is too specific. While it certainly could be used for data on taxa, it can be used for other data types, as well. Would you do a bit more research on that term and revise to make the definition more general? The Wikipedia page on bipartite graphs might be a good place to start. 
- I think you can remove the "data from distances" term. It looks like that's a subsection header in the print book rather than a vocabulary term. 
- For "binary data", I don't think it's only restricted to data structured in matrices. I think you could change this definition to "data in which each observation can take only one of two values (e.g., 0 or 1). 
- For "Overrepresented or enriched", could you change the "or" to "/"? Also, since this term could mean different things in different contexts, you might want to add at the beginning something like "In the context of gene expression, a term to describe"
- In the definition for "perturbed", I'm not sure that you've quite captured the definition yet. I think that the idea is that when a graph is perturbed, a change in one of the nodes (or to one of the nodes) ends up creating changes in other nodes by working through the network. For example, a big disaster in one city might perturb food deliveries to other cities because of perturbations that disaster creates in the transportation network---while the disaster only happens in one city in the network, if it's connected to other cities, that connection creates problems in the other cities, too. [This article](https://www.pnas.org/content/115/27/E6375) might be one place to check out to get a better idea of how to define this term in the context of graphs and networks.
- For "rooted binary trees", could you either change the term to the singular or change the definition to be plural ("data trees" instead of "a data tree")?
- For "cycles", could you add at the beginning "In the context of graphs"?
- For "Contemporaneous data", is this really meant instead to refer to present-day data (or at least, data from about the same time)? In the context of phylogenetic trees, I could imagine that they might be thinking about how we have some data from now on genomics of different species, and from that we can build trees that include connections through ancestors that are now extinct.
- For "gene trees", could you add at the beginning "Structures"?
- For "the generator", would you take off "the"? Also, I recommend adding to the beginning of the definition "In the context of Markov chains," and at the end "describing transitions between steps of the chain"
- For "transition matrix", I recommend adding to the beginning "A matrix that" and at the end "fora Markov chain"
- For "parsimony tree" and "maximum likelihood tree", I recommend adding at the beginning "A structure created using"
- For "Bayesian posterior distributions for trees", perhaps change the beginning to "A method that uses"?
- For "distance-based methods", I think there should be a hyphen in "distance-based". Also, could you change the definition to start "Semi-parametric methods"?
- For "align", could you either change the beginning to "To arrange" or change the term to "aligning"?
- For "sample information", in the book it looks like the term they want to highlight is just "sample". Could you instead define "sample" here? (It's likely already been defined for a previous chapter, and if so you can just copy in that definition.)
- For "jitter", could you change the beginning from "Slightly moving" to "To slightly move"? (Or change the term itself to "jittering"?)
- For "undirected", could you add at the beginning "A term describing"?
- For "associated", could you add at the beginning "A term" and change "indicates" to "indicating"
- For "Friedman-Rafsky", could you change the term to "Friedman-Rafsky tests"?

**Comment by sarahcooper22** [comment]
Hi Brooke,

Sorry I am just now seeing this, I have been swamped with work all week but
am editing right now.

Sarah

**Comment by geanders** [comment]
Thanks, @sarahcooper22 ! @baileyfosdick , did you have any additional edits to make? Otherwise, I will be aiming to get this online by early this afternoon.

**Comment by geanders** [comment]
@sarahcooper22 : I've made a few final edits to the vocab list. Really nice work on it!! You can see my final edits here: https://github.com/geanders/csu_msmb/commit/fa30ff013971b84ac4ad388d3225c2a05f7d9921#diff-d224be24e7a21950ac87483ae169bdc9

Would you make sure that the Quizlet list is up-to-date with the latest version of the list, with these edits included? As long as you change it in Quizlet, you won't need to make any changes to the blogdown code. It embeds whatever's currently showing up in Quizlet.

**Review by sarahcooper22 — COMMENTED** [review]
@geanders I think "Moved practice code to another location, completed exercise 2.6 edits" is the commit and pull request with my completed exercise 2.6 edits, I'm not sure if it worked or not, let me know how things look on your end.

**Comment by geanders** [comment]
My apologies! I think that I missed that. I will take a look and let you know if I have any problems finding that.

**Comment by sarahcooper22** [comment]
No worries! It was buried in there! Let me know if there is anything I can
do to help.

**Pull request merged**
