### PR TITLE
Exercise 2.6

### PR DESCRIPTION
**Pull request by sarahcooper22**

### CODE REVIEW

**Comment by geanders** [comment]
@sarahcooper22 : I'm working on this right now. Just to let you know, I need to remove some of the files that you added to your fork at the top level---these look like some .R and .Rmd files where you've tried out code for some of the chapters and exercises. 

Me changing this on the master branch shouldn't affect your local branch right now, but it will if you later sync your fork with the master. You'll probably do this when you do the vocab assignment. If you want to make sure you keep any of those practice R files, I'd recommend that you make a separate R project for your practice code for the class and move these files there. (Let me know if you have any questions about this, and I can explain more!)

**Comment by geanders** [comment]
@sarahcooper22 : Nice start on this!

There are a number of edits you'll want to make to this. Some are at the level of formatting, some are in the code to get it running, and some are to add some more explanation of what's being done in the code.

I have made some edits to help out. I have mostly made these in the first half of the post, so that you can get an idea of the direction we'll want to go as we finalize the post. You can start by looking at the changes I've made, to get some ideas of how to continue editing to get to the final draft.

Some changes I made to clean up the post, especially in the first part are that I: 

- Put a space after `#` for any section headings. Otherwise (at least on some computer systems), it won't get formatted as a section heading. Instead, it will literally repeat the "#Header wording". 
- Changed to shorter section headings. Since section headings are shown in a larger font, it can get overwhelming if they're too long.
- Put the exercise prompt that you quoted in a "quotation" environment (start the line with `> `), which sets it off as a block quote in the text
- Used the `$` Markdown syntax to put some things in "math" format (for example, to make the Greek letters look Greek)
- Added the code defining the function `loglikelihood` from the book. Each RMarkdown document runs in a "fresh" R session, so any function that isn't defined in base R needs to be redefined inside the RMarkdown document. The RMarkdown session won't be able to use functions defined in your usual R session when you render the full document.
- Broke up the code chunks a bit, so there's less code in each chunk. Among other things, that gives us the chance to get code for plotting a bit more on its own. Then it's easier to customize the figure sizes with chunk options like `fig.width` and `fig.height` if we need to. It also makes it easier to walk the reader through the code in smaller steps.
- For the figure where the density is added to a histogram with `lines`, added code to create the plot before trying to use `lines` to add a line to it. I added the example code from the book for the histogram before this. I think that previously (before breaking up the chunks some), you might have been adding the line to a different histogram, which I don't think is quite what we wanted here (I can explain this more in person if this is unclear--it's a little hard to explain in a written comment).
- Took out `rbinom(length(rtheta), rtheta, size = 300)`. It looked like this was just printing out a random sample, but not storing it anywhere to use later. I think the point in the book about this piece of code was that you can use this kind of vectorized code in place of some of the code in the call `y = vapply(rtheta, function(th) { rbinom(1, prob = th, size = 300)}, numeric(1))`, so you could change to use something like `y =  rbinom(length(rtheta), rtheta, size = 300)`, but you don't need both, and there's no reason to run the `rbinom` call in this case if you're not saving the output anywhere.

Go through the blog post again and take another pass to see if you can make these kinds of changes throughout the blog post. Also, make sure that you test out your post as you go. I think you might have been relying on just running each code chunk by itself, rather than rendering the whole blog post. If you just run a chunk, R will also have access to objects defined in your current R session. When the whole blog post is rendered, however, it does it from a new R session. That means that you need to be very careful to define *everything* you need (objects, functions, etc.) in the RMarkdown code, or it won't render the final version. There were several cases in the code where you skipped a line or two that defined objects or functions that were needed later, so it wouldn't run. I've fixed some of these earlier in the blog post, but there are still some later in the blog post. There are two code chunks at the end that still aren't working---these are places where you'll need to check the code to figure out what objects need to be defined to get these to work. For right now, I've set those code chunks to not run when we render the post (`eval = FALSE` in the code chunk). You can change those (either to `eval = TRUE` or just take them out, since that's the default) once you figure out how to fix the code in those chunks. 

Also, please add some more details throughout to explain exactly what the code is doing. Feel free to ask me or Bailey if there are places where you haven't quite been able to figure it out and we'll be happy to work through it with you.

To get all these changes, you'll need to update your fork from the master repo again (same as you did before starting this post), and then you'll need to open a new pull request once you've made your additional changes, committed them, and pushed them to your GitHub fork. 

As a small note, I also made some small changes to help the post fit into the blog. There are just for you to know, in case you're interested---you won't need to make changes based on them: 

- Changed the blog post title to be consistent with the other exercise solution blog post
- Changed the tags to be consistent with other posts ("Chapter 2", with "C" capitalized [I don't know if tags are case-sensitive?] and "exercises")
- Specified in the YAML at the top of the file that this is currently a draft. We'll change that when the final post is ready to publish.

**Comment by sarahcooper22** [comment]
Hi Brooke,

Thank you for taking the time to look over and edit this! I get those back
to you soon.

Best,
Sarah

**Comment by geanders** [comment]
@sarahcooper22 : Just wanted to check in and see if you'd gotten the chance to revise yet?

**Comment by sarahcooper22** [comment]
Hi Brooke,
I made those revisions a while ago and tried to do a pull request for it.
Did I do something wrong?

**Comment by geanders** [comment]
@sarahcooper22 : Okay, so I think that I found the right version to pull in. I've made some last edits (mostly, moving some explanation text from after code to before) and published it: https://kind-neumann-789611.netlify.app/post/ex-2-6/

Take a look when you get a chance and make sure it looks okay to you---I think I may have managed to mix some versions in committing your vocab post, and if so my apologies! In particular, if there are any changes you'd like, if you let me know I can work them in tomorrow before class.

**Comment by sarahcooper22** [comment]
Hi Brooke,

Sorry for the late response, thank you for taking the time to look through
all of that, it looks great!

Sarah

**Pull request merged**
