### PR TITLE
Added Ch 11 Datasets and Ch 11 Exercise Solution Rmd

### PR DESCRIPTION
**Pull request by melder27**
In the example_datasets subdirectory, I added the 4 datasets required for the exercise. Then I created the Rmd in the post directory, knitted it, and here it is. Please let me know what needs to be changed! Thanks in advance for your feedback!

### CODE REVIEW

**Comment by geanders** [comment]
@melder27 : Yes! This all came through! I'll take a look tomorrow and post some suggestions for edits for the final draft.

**Comment by geanders** [comment]
@melder27 : Great work on this! I have a few suggestions for edits for the final draft. As long as we keep this pull request open, those should come straight through when you push them to your fork on GitHub. 

- For the sentence, "The cell types we will look at are T cells (T_cells), tumor cells (Tumor), dendritic cells (DCs), and other cells (other_cells)."---if the things in parentheses are column names or other values in R, it might make sense to format them in the text with backticks so they'll show up as code in the text rather than regular text. 
- It's really nice how you're loading all the packages and the beginning and also showing how to install packages that people might need but not have. 
- Do you mean to have the code chunk where you read in the data not print? Right now, that code chunk has `include = FALSE` as a chunk option, so none of your code is showing up in the blog post for that part. 
- When you give an overview of the data, could you explain what each of the three columns is measuring, as well as what each row (observation) is? If I remember correctly, I think that each row represents a cell identified in that image of the lymph node, with the `x` and `y` giving the cell's location in the image and the `class` telling which type of cell it is.
- When you visualize the position of each cell using that first `ggplot` call, could you add just a bit of text describing what patterns we can already see, just from this initial exploratory analysis, before we get into any statistical analysis? For example, it already looks pretty clear that some of the cell types (like the tumor ones) *very* clearly cluster together in a few groups, while some of the others . 
- Take a pass through and make sure you're being consistent in using backticks around R object names or package names in the text. Doing this helps readers' brains process the text, since they can more quickly recognize that a word isn't something they need to process in English. A few places where you've missed this formatting in the current draft (at least at some point when you use the word) are (and generally you've done a really great job of catching almost all of these!): spatstat, Lpois. Also, for ppp, you put that in quotation marks, which can work, but I think backticks could work for that, too. 
- When you convert the data to a `ppp` object with the `ppp` function, could you add just a bit, either in the text or the code comments, to explain what you need to input into that `ppp` call? (for example, what do you need to put in for the `x`, `y`, etc., parameters?)
- Very nice explanation of why we're adding in info about the hull in this object!
- This code (from the book, I know!) is a bit of a bear to figure out: 

```
idx = integer(nrow(chull) + 1)
pidx[1:2] = chull[1, ]
chull[1, ] = NA
for(j in 3:length(pidx)) {
  wh = which(chull == pidx[j-1], arr.ind = TRUE)
  stopifnot(nrow(wh )== 1)
  wh[, "col"] = 3 - wh[, "col"] ## 2->1, 1->2
  pidx[j] = chull[wh]
  chull[wh[, "row"], ] = NA
}
pidx = rev(pidx)
```

Could you add a few more code comments throughout this piece to explain what's going on? You've got some nice comments on *why* they need to do this, but it's still hard to figure out what's going on just by reading through the code. 
- Maybe add on to the sentence, "Now that we have defined the hull as a closed polygon, we can convert our data into a “ppp” object class." something like ", adding the hull information with the `poly` parameter in the `ppp` call". Just to make that final connection of how the hull information is making it into the object. 
- Generally, really helpful code comments throughout this section!
- Really nice explanation of the goal of the statistical analysis! Also, you've got some really nice text explaining some of the `spatstat` functions that are being used. Nice work!
- In the section on "Investigating Spatial Dependence", could you add a bit of text to explain to the reader how to interpret each type of graph when you first show it? For example, what should they be looking for in the "Gest(ln)" plot? What are you looking for that allows you to conclude "While it looks like our data may differ from a homogenous Poisson CDF, the general shape of our data seems to support this distribution is a fairly reasonable assumption."? For the L function plot, what's being shown by the "r" value on the x-axis? Is this the distance to the nearest neighboring cell of that type? You've done a really great job of providing an interpretation of the plots for this data, so it would be really nice to add just a bit first explaining how to look at each of these types of plots.
- In the sentence, "If we want to estimate the L function (see equations 11.10 and 11.11 in the book for details),", it's fine to point the readers to those equations for more details, but could you add just a few words to give a top-level explanation of what the L function measures?
- In places where you talk about the plots, it might be helpful to reference objects on the graph by color. For example, in the text, "The distance estimator for the border-corrected estimate and modified border-corrected estimate of the L function for T cells ", maybe add "(red line)" and "(green line)" to direct the readers to certain elements of the plot as you discuss them?
- For the L function plots, could you briefly explain why you see more lines for some cell types (e.g., the dendritic cells) versus others? Based on the message you get in the code output, I'm guessing it's related to the number of cells in each class, and the function defaults to only calculate certain functions if you have too many cells in a group (more than 1,000). I wonder if that's something that could be changed with one of the function parameters in the `Linhom`function?
- Could you add a few words explaining the difference between the border-corrected estimate and the modified border-corrected estimate?
- Very nice interpretation of the pcf plots! In particular, it's really interesting how your results can help in hypothesizing that tumor cells might have a larger volume than some of the other types of cells. It might be interesting to know, too, if this follows biological knowledge about these cell types?
- Very nice work with bringing it all together with your final paragraph!

**Comment by melder27** [comment]
Hi Dr. Anderson,

I just wanted you to know I may not be able to get to this all by class tomorrow, but I will definitely mark off things as I can in the next few days and let you know when I've implemented your feedback! Thanks for taking the time to review it all and help me with the post! 

Thanks,
Mikaela

**Comment by geanders** [comment]
@melder27 : That's completely understandable! Would you still be willing to give an overview of what we have during our class tomorrow? I think that you have a very nice draft already.

**Comment by melder27** [comment]
Oh, absolutely! I just wanted to make sure I let you know I'll be working on it but won't have all of the feedback implemented by then.

**Comment by geanders** [comment]
Sounds great! Thanks for letting me know.

**Comment by geanders** [comment]
@melder27 : I just wanted to quickly check in on this. We have our due date for turning in grades this week (Tuesday by 2:00 is the preferred time, but it looks like they will allow us to submit through Wednesday afternoon, I think). Do you think you'll be able to finalize this today or tomorrow morning? Otherwise, perhaps we should chat briefly to make sure we can figure out a good plan for an alternative schedule.

**Comment by melder27** [comment]
@geanders : Here is how I have incorporated your feedback. I'll push it back to the fork on GitHub. Please let me know if you don't see it. 

- For the sentence where I had parentheses around the names of the columns in the dataframe, I changed it to backticks instead.

- For the code reading in the data, I don't think I meant for it to not show up in the document so I changed it to echo=true.

- After reading in the data (and before displaying the first few rows of the dataframe), I incorporated a description of what the data looks like and represents. Please let me know if this is not what you had in mind for your overview of the data feedback.

- I added a couple of comments after the visualization of the data with ggplot describing the clustering of the tumor cells, and potentially even the other cell types. 

- I did a command+F for spatstat, ggplot, Lpois, and ppp to make sure they were all represented using backticks. Please let me know if you find something else that should be formatted that way and isn't.

- I added some explanation before running the `ppp` function about parameters we can use (or that are required) to input into the function. 

- I did my best with the comments on the book's code that create `pidx` for the hull. Let me know if there's something that needs to change.

- I added an explanation about using `poly` with the `ppp` function after creating the hull.

- There is now more context for the "Gest(ln)" plot and what we are looking for in the plot.

- Context and explanation have been added about the L function estimates and their plots. For the pcf plots, I included an explanation of what the axes are.

- In the introduction of the L function section, I added some context for what type of information we are looking at or hope to gain from looking at estimates using the L function.

- Color references to the L estimate graphs were added, along with what the estimates were using notation from the legend.

- A section was added under the L estimate of DCs to explain why we ended up with two additional estimates not seen in T cells or tumor cells. I included a link to the `Kest` R documentation that discusses this and provides a citation for where people can find more information about the different estimate corrections.

- Finding information about the difference between border corrected and modified border corrected information took awhile. I included a link to the source of the information I used, as I thought it was described in a digestible way and included other types of corrections for inhomogenous estimation. It isn't peer-reviewed though, so let me know if this source is inaccurate or has other issues.

- The second to last paragraph now includes biological relevance (and intuition) behind our results. 

- I added a references section for where I found the information about T cells and DCs in lymph nodes. 

The document is currently being knitted before I push it onto the fork. 

Thanks for your time and feedback! I greatly appreciate it!

**Comment by geanders** [comment]
@melder27 : Great, thank you! This sounds great!

**Comment by melder27** [comment]
@geanders I pushed the updated file onto the fork yesterday, and I just wanted to check in and see if there were any additional changes that needed to be made.

**Comment by melder27** [comment]
@geanders : I know you've probably been very busy, but I just wanted to check and see if there was anything that I should change in the Rmd file so that the post could be put on the website.

**Comment by geanders** [comment]
@melder27 : Sorry for the delay! No, it all looks good. I will get it up today!

**Comment by melder27** [comment]
@geanders : Sounds good. Thanks for taking the time to review it and for letting me know!

**Comment by geanders** [comment]
It's now live: https://kind-neumann-789611.netlify.app/post/exercise-solution-for-chapter-11/
Nice work, and thanks again for the reminder for getting it merged in!

**Pull request closed without merging**
