### PR TITLE
Chapter 5 Vocabulary 

### PR DESCRIPTION
**Pull request by bkarger**

### CODE REVIEW

**Comment by geanders** [comment]
@bkarger : Great! These changes all seem to have come through really well. We'll take a look over the definitions and get back to you with some requests and suggestions.

**Comment by geanders** [comment]
Really nice job, @bkarger, and I know you got a really long list this week!

I've gotten started with a few suggestions from my end: 

- [ ] Take a pass through and make sure that you edit any cases where the term is included in the definition (see the definitions for "Manhattan distance" and "status" for examples). (These would be a little too easy in the vocab quiz...)
- [ ] There's a typo in "Weighted Euclidean distanc"
- [ ] The definition for "Jaccard index" is really nice. I don't think the definition for "Jaccard distance" is right, though. It describes why you might want to use this and how you code the data, but not how you calculate that distance. Could you double-check that definition with another source?
- [ ] For the "binary distance" definition, I suggest adding to the beginning "A metric of distance between two binary strings based on"
- [ ] For the definition for "Minkowski distance", maybe change "which can be considered as a generalization of both the Euclidean distance and the Manhattan distance" to "that encompasses both the Euclidean and Manhattan distance, incorporating a parameter to allow this generalization"
- [ ] For the "distance" definition, you're on a good start, but I recommend editing to simplify to: "a measure of the differences between random variables"
- [ ] For the definition for "unsupervised method", you've certainly described a key characteristic, but I'm not sure that's quite the definition. Maybe: "a learning method where all variables are treated with the same status, rather than one variable being considered as an outcome or target"
- [ ] For "Jaccard dissimilarity", would you make the spacing the same around the "-" (either a space on both sides or on neither)
- [ ] For "correlation-based distance", could you add at the beginning "a distance measure that". Also, to shorten this definition, you can take off the sentence at the end ("The distance between two objects is 0 when they are perfectly correlated.").

This goes through the top part of the list. I need to run to something else right now, but I'll add comments on later definitions later.

**Comment by geanders** [comment]
Alright, moving down the list, here are some more suggestions: 

- [ ] Again, for "CDs", be sure to take the term out of the definition so it will work on flashcards and the vocab quiz. Here's a suggestion for that change: "Unique combinations of proteins that immune cells express on their surfaces at different stages of their development"
- [ ] Same for rectangular gating. Would it be correct to change that to something that talks about a method of identifying groups of cells from a flow cytometry experiment using either a line (one-dimensional) or the quadrants created by two perpendicular lines (two-dimensional)? (Also, just to clarify, can't rectangular gating be used when you're dividing based on two markers, and you divide the region into four quadrants? Or is it really just for one-dimensional separation?
- [ ] For the definition for "Hyperbolic Arcsine", the current definition explains why / when you would use that transform, but not what it is. Also, you might want to include in the definition for this term that it is "a transform function often preferred over the log tranform for flow cytometry data because it can be applied to negative values". We can talk some more about how to get this definition right, because while I normally like to be pretty precise with these, I certainly don't think we want to put the whole math equation for this transform in---that would be overkill.
- [ ] I noticed that you have some non-ASCII characters in some definitions ("dbscan", for example). Just curious---do those work okay in Quizlet?
- [ ] For "curse of dimensionality", you might want to add "that arises because, when the dimensionality increases, the volume of the space increases so fast that the available data become sparse" 
- [ ] For all of the distance metrics, would you start them in a consistent was with something like "a distance metric based on..." Similarly, for a collection of methods in a certain class, it would be helpful to start the definitions in a similar way, so the students will start to see which ideas are in the same class. For example, for different clustering methods, you could start with "a clustering method that ..."
- [ ] For "technical / batch effects", I would recommend editing to something like "Depedence in data observations that results from technical differences between samples, such as the type of sequencing machine or the technician that ran the sample, rather than from scientifically interesting causes."

I'll continue adding suggestions when I get another chance to dive in.

**Comment by geanders** [comment]
For the next words on the list: 

- [ ] For "neighbor cluster", could you add at the end "for a given cluster"?
- [ ] For "computational complexity", a more general definition would be helpful. For example, something like "a measure capturing the computational resources usually needed to solve an algorithm"
- [ ] For "recursive partitioning methods", I suggest editing what you have to "A class of methods for dividing heterogeneous populations into more homogeneous subgroups, often used to make decision trees, that starts by separating the whole population into a few groups and iteratively continues separating each into subgroups".  For this definition, I think what's important is to capture that this is a pretty "top down" approach---it starts by dividing the full group and then progressively divides into more and more groups. On the other hand, there are other partitioning methods that cluster from the bottom up, starting with some data points and building up clusters from those. 
- [ ] For the "minimal jump method entry", could you add at the beginning something like "a clustering method that" (same comment for "maximum jump method", "average linkage method", and "Ward's method")
- [ ] For "noise", I recommend just using the first sentence that you currently have ("Unexplained variability within a data sample")
- [ ] For the definition for BSS, I recommend editing to "A measure of the interaction between the groups or samples that is small if the group means don’t differ greatly from each other and the overall mean"
- [ ] For "silhouette index", I recommend you remove "refers to" and just start with "a method...". Also, I think it would make sense to change from "a method of" to "a metric for". Typically, an index is just a way to measure something, and then you might use it in some method.
- [ ] For "filtering", could you move the note "in the context of filtering out low-quality rRNA reads" into the definition, so the term is just "filtering" and then the definition is "in the context of rRNA reads, the process of removing low-quality reads and trimming them to a consistent length"
- [ ] For "indel", a simpler definition would work, like " insertion or deletion of bases in the genome of an organism"
- [ ] For "rare variant", could you start the definition with "an alternative form of a gene that"
- [ ] For the single cell RNA-seq term, could you change "provides" to "a measurement of". Also, could you specify what type of expression this is measuring (e.g., "gene expression" rather than just "expression"). I don't know---are there different types of expression you would measure, or is "expression" clearly shorthand for gene expression and only that in this context?
- [ ] For the "immune cells" definition, can you change the start of the definition from "cell" to "cells" and "is" to "are" (and "helps" to "help")?
- [ ] For "CD marker", can you change the term itself to "CD marker / antigen marker" and then in the definition remove everything before "specific types" (so delete "CD markers, also known as CD antigens, are ")?
- [ ] For "variable regions", could you move "in the context of taxon identification of bacteria" from the term to the start of the definition? (so the term itself would only be "variable regions")
- [ ] For "representativeness heuristic", could you replace the beginning of the term up to "similarity" with "a method of learning or discovery that assesses..." 
- [ ] For "OTU clustering", I think there are a few definitions, and I think our book might be referring to a slightly different (or more specific) one that you've put here. I recommend changing this definition to something like "A method of clustering organisms based on DNA sequence similarity of a certain taxonomic marker gene"
- [ ] For the "gap statistic" term, I found a really nice blog post that talks about this and I think has wording that would be helpful for the definition (https://vsoch.github.io/2013/the-gap-statistic/). Based on that description, I think your definition here could be something like "a metric develope to help approximate the 'correct' number of clusters for an unsupervised clustering by measuring the within cluster sum of squares with regard to the number of clusters." If you use this definition, be sure to add that blog post to your "Sources Cited" section in your blog post.
- [ ] For the "WSS" term, I think you could use something simpler, like "a measure of the difference among data points within an identified cluster"

**Comment by geanders** [comment]
@baileyfosdick : I think this is ready for you to add your comments. Let me know when we're set, and I'll get it merged into the main branch and up online.

**Comment by baileyfosdick** [comment]
@geanders Great! I will fix this up tomorrow morning and then we can get it posted.

**Comment by baileyfosdick** [comment]
@geanders Good to go!  Nice work Burton!

**Comment by geanders** [comment]
Great! I'm getting this up this morning. @bkarger : Just a reminder--have you also updated the Quizlet list? If not, could you do that when you get a chance?

**Comment by geanders** [comment]
Regarding Quizlet, in particular there there two terms where the tab had gone missing between the term and definition (probably during our editing process). These are the OTU and indel definitions. If you update Quizlet with the new tsv, I've fixed that in the tsv, so it should fix those two terms on Quizlet.

**Comment by geanders** [comment]
Now live: https://kind-neumann-789611.netlify.com/post/vocabulary-for-chapter-5/
Great work on this, @bkarger

**Comment by geanders** [comment]
@bkarger : Just to let you know, I need to remove some of the files that you added to your fork at the top level---these look like some .R and .Rmd files where you've tried out code for some of the chapters and exercises. 

Me changing this on the master branch shouldn't affect your local branch right now, but it will if you later sync your fork with the master. You'll probably do this when you do the exercise assignment. If you want to make sure you keep any of those practice R files, I'd recommend that you make a separate R project for your practice code for the class and move these files there. (Let me know if you have any questions about this, and I can explain more!)

**Comment by bkarger** [comment]
Brook,

Sounds good!

I have fixed it on my quizlet set and looks like it is rendering correctly
now.

Is there anything else I need to do for the vocab??

Thanks,

Burton

**Comment by geanders** [comment]
You're all set!

**Pull request merged**
