### PR TITLE
Add Ch. 4 Vocab

### PR DESCRIPTION
**Pull request by aef1004**
I was having problems with updating my fork, but hopefully this should still work

### CODE REVIEW

**Comment by geanders** [comment]
@aef1004 : I don't see anything here in the conflicting files that is likely to create a big problem when we merge in your branch, so I think we're good to go from the mechanical standpoint. The other faculty and I will look over the vocabulary and make suggestions in the next few days.

**Comment by geanders** [comment]
(Also, in terms of figuring out what happened, my best guess is that you might have missed doing the step of adding the remote---`git remote add upstream git@github.com/geanders/csu_msmb.git`---before trying to pull the changes.)

**Comment by geanders** [comment]
@aef1004 : Very nice start on this! Technically, it looks like everything's looking good. I do have some suggestions for your definitions, and @baileyfosdick and @lyonsm7 might as well. Any changes you make and push to your GitHub version of the repo should be automatically added to this pull request, as long as we keep it open. 

As a first comment, I was noticing that some of the terms here have similar ones in the previous chapter. That vocab was merged into the repo after you had your list, so I know that you didn't have access to it. I think it would be nice, though, to do what we can to keep the language specific. Here are a few suggestions along those lines (I'm doing these as checkboxes, so you can check off as you go along if it's helpful): 

- [ ] For "bimodal distribution", change "peaks" to "modes"
- [ ] It would be great if we could make the "finite mixture" and "infinite mixture" definitions more consistent with those for Ch. 2, which defines mixture as "in the context of statistics, when the distribution of interest is a combination of two or more different probability distributions". Maybe, "in the context of statistics, when the distribution of interest is a combination of a few different probability distributions" for "finite mixture", for example, and a similar change for "infinite mixture"?
- [ ] Similarly, we could try to make "marginal likelihood" more consistent with the definition for "marginal distribution" given for Ch. 2 (which was "the distribution of a sub-collection of variables after integrating out the remaining variables in the collection"). 

Also, for a few other things: 

- [ ] Please check throughout that the grammar used for the term agrees with that of the definition. For example, "latent variable" is the term (singular), but "variables" is how the definition starts (plural).
- [ ] There is a typo ("proabailistic") in the definition for EM algorithm.
- [ ] There is also a typo ("dstirubtion") in the definition for bootstrap.
- [ ] There is also a typo ("samplin distriubtion") in the definition for nonparametric bootstrap. Also there is the typo "assumptionf or" in this definition.
- [ ] There is also a typo (" varaicne") in the definition for heteroscedasticity. 
- [ ] I think there should be a hyphen in "zero-inflated".
- [ ] For "infinite mixture", I think it could also have *more* components than observations. 
- [ ] We are finding that there are a few terms that are in bold in the print version of the book, but not online, and we're asking students to add these to their list. For this chapter, there are a few bolded terms from the print book that are not yet in your list: **mixture model** (in 4.2.1---you could base your definition for this off a definition for *mixture* in part 2 of Chapter 2), **density function** (in 4.2.1---this may have an existing definition from a previous chapter that you could use), **mixture fraction** (in 4.2.2), **identifiability** (in 4.2.2), **expectation function** (in 4.2.2), **maximization step** (in 4.2.2), **soft averaging** (in 4.2.2), **empirical cumulative distribution function** (in 4.3), **density** (in 4.3), **non-parametric methods** (in 4.3), **Laplace distribution** (in 4.4.1), **gamma distribution** (in 4.4.3)
- [ ] Even though this chapter didn't have many (or any?) biological terms in bold, it would be nice to add a few, especially for those in the class with less of a biology background. I think these would make sense: **ChIP-Seq data** (in 4.2.3), **chromosome** (in 4.2.3), **binding site** (in 4.2.3), **deoxyribonucleotide monophosphates** (in 4.2.4), **gene expression** (in 4.4.1), **microarray** (in 4.4.1), **promoter** (shown in Figure 4.17),

**Comment by aef1004** [comment]
@geanders I've updated the vocab with your suggestions. I was a little bit unsure on three of the terms: identifiability, expectation function, and deoxyribonucleotide monophosphate. 

I was also still having a few problems with being able to view the updated website on my own computer, but I think everything should be okay.

**Comment by aef1004** [comment]
Regarding the forking, I had the git remote add upstream and it returns: "Fatal: remote upstream already exists." When I pull the upstream master, it says that the git@github.com/geanders/csu_msmb.git "does not appear to be a git repository."

Screen Shot 2020-02-18 at 8 30 12 PM

**Comment by geanders** [comment]
For the fork update---yes, it certainly looks like you added the remote correctly. Looking at the code, there's a chance that one spot in the remote address should be a colon instead of a forward slash. It would be quickest if we check that in class. We'll need to have you remove that existing remote and then try the new one, and I can show you how to do that pretty quickly in person.

**Comment by geanders** [comment]
@aef1004 : Another student is getting the same error when she tries to update her fork. I gave her a suggestion to try if it is a problem from a typo in the code I originally posted for my suggestion to fix this. If you get a chance, try out the fix I suggested for her in [our discussion of her pull request](https://github.com/geanders/csu_msmb/pull/37).

**Comment by geanders** [comment]
@aef1004 : I just made a few small wording changes to your vocabulary here (in commit [7e6bc34](https://github.com/geanders/csu_msmb/pull/35/commits/7e6bc34d0fed349cac9f479471ee42c68f8e8347)), but otherwise this satisfies everything I brought up in my comments. We'll see if @baileyfosdick or @lyonsm7 have any suggestions for edits and then we'll merge this in and make it public on the webpage. (Also, don't forget to update your Quizlet word list with the latest version of the list once it's finalized.)

**Comment by aef1004** [comment]
Thanks! I updated the Quizlet as well.

To be honest, I didn't realize how much I rely on Word and Google docs to autocorrect all the words that I type so thank you for fixing those typos!

**Comment by geanders** [comment]
Oh, same! (regarding autocorrect)

**Comment by geanders** [comment]
Great! I've merged your changes into our master branch. I've set the post to be a "draft" for now---we'll change that after class today, once we can check in with the other faculty about whether they have edits.

**Pull request merged**
